/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_htfyun_uartJni_UartJni */

#ifndef _Included_com_htfyun_uartJni_UartJni
#define _Included_com_htfyun_uartJni_UartJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_htfyun_uartJni_UartJni
 * Method:    uartSetSpeed
 * Signature: (II)V
 */
JNIEXPORT jboolean JNICALL Java_com_htfyun_uartJni_UartJni_uartSetSpeed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_htfyun_uartJni_UartJni
 * Method:    uartSetParity
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_htfyun_uartJni_UartJni_uartSetParity
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_htfyun_uartJni_UartJni
 * Method:    openUartChannel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_htfyun_uartJni_UartJni_openUartChannel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_htfyun_uartJni_UartJni
 * Method:    closeUartChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_htfyun_uartJni_UartJni_closeUartChannel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_htfyun_uartJni_UartJni
 * Method:    uartWriteBytes
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_htfyun_uartJni_UartJni_uartWriteBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_htfyun_uartJni_UartJni
 * Method:    uartReadBytes
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_htfyun_uartJni_UartJni_uartReadBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
